name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8' # Replace with your Python version

    - name: Install Project Dependencies
      run: pip install -r requirements.txt

    - name: Lint with Pylint
      run: pylint *.py

    - name: Run Unit Tests
      run: pytest

    - name: OSSF Scorecard action
      uses: ossf/scorecard-action@v2.3.1
            

    - name: Lint Dockerfile
      uses: hadolint/hadolint-action@v1.5.0
      with:
        dockerfile: ./Dockerfile

    - name: Build Docker image
      run: docker build . --file Dockerfile --tag your-image-name
